/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FollowerRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.helix.tables.records.FollowerRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -58351856;

	/**
	 * Setter for <code>public.follower.user_id</code>.
	 */
	public void setUserId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.follower.user_id</code>.
	 */
	public java.lang.Long getUserId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.follower.following_id</code>.
	 */
	public void setFollowingId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.follower.following_id</code>.
	 */
	public java.lang.Long getFollowingId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return tech.codingclub.helix.tables.Follower.FOLLOWER.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return tech.codingclub.helix.tables.Follower.FOLLOWER.FOLLOWING_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getFollowingId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FollowerRecord value1(java.lang.Long value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FollowerRecord value2(java.lang.Long value) {
		setFollowingId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FollowerRecord values(java.lang.Long value1, java.lang.Long value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FollowerRecord
	 */
	public FollowerRecord() {
		super(tech.codingclub.helix.tables.Follower.FOLLOWER);
	}

	/**
	 * Create a detached, initialised FollowerRecord
	 */
	public FollowerRecord(java.lang.Long userId, java.lang.Long followingId) {
		super(tech.codingclub.helix.tables.Follower.FOLLOWER);

		setValue(0, userId);
		setValue(1, followingId);
	}
}
