/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tweet extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.TweetRecord> {

	private static final long serialVersionUID = -1517146872;

	/**
	 * The singleton instance of <code>public.tweet</code>
	 */
	public static final tech.codingclub.helix.tables.Tweet TWEET = new tech.codingclub.helix.tables.Tweet();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.TweetRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.TweetRecord.class;
	}

	/**
	 * The column <code>public.tweet.message</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.TweetRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(160), this, "");

	/**
	 * The column <code>public.tweet.id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.TweetRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.tweet.created_at</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.TweetRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.defaulted(true), this, "");

	/**
	 * The column <code>public.tweet.author_id</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.TweetRecord, java.lang.Long> AUTHOR_ID = createField("author_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * Create a <code>public.tweet</code> table reference
	 */
	public Tweet() {
		this("tweet", null);
	}

	/**
	 * Create an aliased <code>public.tweet</code> table reference
	 */
	public Tweet(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Tweet.TWEET);
	}

	private Tweet(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.TweetRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tweet(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.TweetRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<tech.codingclub.helix.tables.records.TweetRecord, java.lang.Long> getIdentity() {
		return tech.codingclub.helix.Keys.IDENTITY_TWEET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Tweet as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Tweet(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Tweet rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Tweet(name, null);
	}
}
